CREATE TABLE `crud_table` (
  `id` varchar(36) NOT NULL,
  `TABLE_NAME` varchar(20) NOT NULL COMMENT '表名',
  `MENU_NAME` varchar(50) NOT NULL COMMENT '菜单名',
  `MODULE_NAME` varchar(50) NOT NULL COMMENT '模块名',
  `MODULE_CODE` varchar(20) NOT NULL COMMENT '模块代码',
  `ENTITY` varchar(255) NOT NULL COMMENT '实体类名',
  `ENTITY_BEAN` varchar(255) DEFAULT NULL COMMENT '实体类作为bean的名称',
  `ENTITY_PACKAGE` varchar(255) NOT NULL COMMENT '实体类包路径',
  `CONTROLLER_URL` varchar(255) NOT NULL COMMENT '控制器映射路径',
  `CONTROLLER` varchar(255) NOT NULL COMMENT '控制器类',
  `CONTROLLER_BEAN` varchar(255) DEFAULT NULL COMMENT '控制器类作为bean的名称',
  `CONTROLLER_PACKAGE` varchar(255) NOT NULL COMMENT '控制器包路径',
  `SERVICE` varchar(255) NOT NULL COMMENT '服务层类',
  `SERVICE_BEAN` varchar(255) DEFAULT NULL COMMENT '服务层作为bean的名称',
  `SERVICE_PACKAGE` varchar(255) NOT NULL COMMENT '服务层包路径',
  `LIST_URL` varchar(255) NOT NULL COMMENT '列表映射',
  `LIST_JSP` varchar(255) NOT NULL COMMENT '列表JSP',
  `ADD_URL` varchar(255) NOT NULL COMMENT '新增映射',
  `ADD_JSP` varchar(255) NOT NULL COMMENT '新增JSP',
  `UPD_URL` varchar(255) NOT NULL COMMENT '修改映射',
  `UPD_JSP` varchar(255) NOT NULL COMMENT '修改JSP',
  `MYBATIS_XML` varchar(255) NOT NULL COMMENT 'mybatis的xml配置',
  `OP_USER_ID` varchar(36) DEFAULT NULL COMMENT '操作用户',
  `OP_TIME` datetime DEFAULT NULL COMMENT '操作时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_crud_table_table_name` (`TABLE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8